version: '3.8'

services:
  # Backend service (Spring Boot)
  post-service:
    build:
      context: ./backend-java/Microservices/post-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/newsflow_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-web/news-flow-app
    ports:
      - "80:80"
    depends_on:
      - post-service

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: newsflow_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Map MySQL to host port 3306

volumes:
  mysql_data:  # Persistent storage for MySQL data
