server:
  port: 8030

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
                - "http://localhost:4200"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders:
                - "*"
              allowCredentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/postService/**
          filters:
            - RewritePath=/postService/(?<path>.*), /$\{path}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviewService/**
          filters:
            - RewritePath=/reviewService/(?<path>.*), /$\{path}

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/commentService/**
          filters:
            - RewritePath=/commentService/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/




